export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const SEND_CODE = 'SEND_CODE'
export const UPDATE_USER = 'UPDATE_USER'